INSERT INTO "Empleado" ("Usuario","Contraseña","Nombre","Apellido1","Apellido2") 
VALUES('Jose216','123123','Jose','Rodriguez','Rojas'),('Emarin19','123123','Emanuel','Marin','Gutierrez'),('Camanem','123123','Oscar','Soto','Varela'),('Seballoll','123123','Sebastian','Chen','Cerdas'),('MRivera83','123123','Marco','Rivera','Meneses');

INSERT INTO "Avion" ("Matricula","Nombre")
VALUES ('C1728CR','TECAir113'),('C4509CR','TECAir114'),('C8424CR','TECAir115'),('C9128CR','TECAir116'),('C8485CR','TECAir117'),('C4952CR','TECAir118');

INSERT INTO "Universidad" ("Id","Nombre","Ubicacion")
VALUES (1,'Tecnologico de Costa Rica','Cartago, Costa Rica'), (2,'Universidad de Costa Rica','San Jose, Costa Rica'), (3,'Universidad Nacional','Heredia, Costa Rica'),(4,'Universidad Tecnica Nacional','Alajuela, Costa Rica'),(5,'Universidad Estatal a Distancia','San Jose, Costa Rica');

INSERT INTO "Aeropuerto" ("Id","Nombre","Ubicacion")
VALUES ('ABC','Aeropuerto de Albacete','Albacete, España'),('AEP','Aeroparque Jorge Newbery','Buenos Aires, Argentina'),('AFA','Aeropuerto Internacional Suboficial Ayudante Santiago Germano','San Rafael, Argentina'),('AGP','Aeropuerto de Málaga-Costa del Sol','Málaga, España'),('ALC','Aeropuerto de Alicante-Elche Miguel Hernández','Alicante, España'),('AMS','Aeropuerto de Ámsterdam-Schiphol','Ámsterdam, Países Bajos'),
('ANF','Aeropuerto Andrés Sabella','Antofagasta, Chile'),('AOL','Aeropuerto Internacional de Paso de los Libres','Paso de los Libres, Argentina'),('ARI','Aeropuerto Internacional Chacalluta','Arica, Chile'),('ARN','Aeropuerto de Estocolmo-Arlanda','Estocolmo, Suecia'),('ASU','Aeropuerto Internacional Silvio Pettirossi','Asunción, Paraguay'),('ATH','Aeropuerto Internacional Eleftherios Venizelos','Atenas, Grecia'),
('AUA','Aeropuerto Internacional Reina Beatrix','Oranjestad, Países Bajos'),('BBA','Aeródromo Balmaceda','Balmaceda, Chile'),('BCN','Aeropuerto de Barcelona-El Prat','Barcelona, España'),('BHI','Aeropuerto Comandante Espora','Bahía Blanca, Argentina'),('BIN','Aeropuerto de Bamiyán','Bamiyán, Afganistán'),('BIO','Aeropuerto de Bilbao','Bilbao, España'),('BOD','Aeropuerto de Burdeos-Mérignac','Burdeos, Francia'),
('BOG','Aeropuerto Internacional El Dorado','Bogotá, Colombia'),('BPM','Base Aérea de Bagram','Bagram, Afganistán'),('BRC','Aeropuerto Internacional Teniente Luis Candelaria ','San Carlos de Bariloche, Argentina'),('BSL','Aeropuerto de Basilea-Mulhouse-Friburgo','Basilea, Mulhouse, Friburgo, Francia'),('BST','Aeropuerto de Bost','Lashkar Gah, Afganistán'),('BUD','Aeropuerto de Budapest-Ferenc Liszt','Budapest, Hungría'),
('COR','Aeropuerto Internacional Ing. Ambrosio Taravella','Córdoba, Argentina'),('CDT','Aeropuerto de Castellon','Castellon,España'),('CCC','Aeropuerto Internacional de Jardines del Rey','Cayo Coco, Cuba'),('CCP','Aeropuerto Carriel Sur','Concepción, Chile'),('CCS','Aeropuerto Internacional de Maiquetía Simón Bolívar','Caracas, Venezuela'),('CDG','Aeropuerto de París-Charles de Gaulle','París, Francia'),
('CGN','Aeropuerto Internacional de Colonia/Bonn Konrad Adenauer','Colonia, Bonn, Alemania'),('CLO','Aeropuerto Internacional Bonilla Aragón','Cali, Colombia'),('CLX','Aeropuerto Clorinda','Clorinda, Argentina'),('CMN','Aeropuerto Internacional Mohammed V','Casablanca, Marruecos'),('CNQ','Aeropuerto Internacional Doctor Fernando Piragine Niveyro','Ciudad de Corrientes, Argentina'),('COC','Aeropuerto Comodoro Pierrestegui','Concordia, Argentina'),
('CTC','Aeropuerto Coronel Felipe Varela','San Fernando del Valle de Catamarca, Argentina'),('CUE','Aeropuerto Internacional Mariscal Lamar','Cuenca, Ecuador'),('CUU','Aeropuerto Internacional General Roberto Fierro Villalobos','Chihuahua, México'),('CVU','Aeropuerto de Corvo','Isla de Corvo, Portugal'),('CWB','Aeropuerto Internacional Afonso Pena','Curitiba, Brasil'),('DAY','Aeropuerto Internacional James M. Cox-Dayton','Dayton, Estados Unidos'),
('DJE','Aeropuerto Internacional de Yerba-Zarzis','Yerba (Túnez), Túnez'),('DME','Aeropuerto Internacional de Moscú-Domodédovo','Moscú, Rusia'),('DOH','Aeropuerto Internacional Hamad','Doha, Catar'),('DXB','Aeropuerto Internacional de Dubái','Dubái, Emiratos Árabes Unidos'),('EAP','Aeropuerto de Basilea-Mulhouse-Friburgo','Basilea, Mulhouse, Friburgo, Francia'),('EDI','Aeropuerto de Edimburgo','Edimburgo, Reino Unido'),
('EGE','Aeropuerto Regional del Condado de Eagle','Eagle-Vail, Estados Unidos'),('EIN','Aeropuerto de Eindhoven','Eindhoven, Países Bajos'),('EPA','Aeropuerto El Palomar','Área metropolitana de Buenos Aires, Argentina'),('ESR','Aeródromo Ricardo García Posada','El Salvador (Chile), Chile'),('EZE','Aeropuerto Internacional Ministro Pistarini','Ezeiza, Argentina'),('ENO','Aeropuerto Teniente Amín Ayub González','Encarnacion (Paraguay), Paraguay'),
('EOH','Aeropuerto Enrique Olaya Herrera','Medellín, Colombia,Colombia'),('FAO','Aeropuerto de Faro',' Portugal,Faro'),('FBD','Aeropuerto de Fayzabad',' Afganistán,Fayzabad'),('FCO','Aeropuerto de Roma-Fiumicino',' Italia,Roma'),('FDO','Aeropuerto Internacional de San Fernando',' Argentina,San Fernando'),('FLR','Aeropuerto de Florencia',' Italia,Florencia'),('FLW','Aeropuerto de Flores',' Portugal,Isla de Flores'),('FMA','Aeropuerto Internacional de Formosa',' Argentina,Ciudad de Formosa'),
('FNC','Aeropuerto Internacional Cristiano Ronaldo',' Portugal,Funchal'),('FRA','Aeropuerto de Fráncfort del Meno',' Alemania,Fráncfort del Meno'),('FRS','Aeropuerto Internacional Mundo Maya',' Guatemala,Santa Elena de la Cruz'),('FOR','Aeropuerto Internacional Pinto Martins',' Brasil,Fortaleza'),('FTE','Aeropuerto Internacional Comandante Armando Tola',' Argentina,El Calafate'),('GDL','Aeropuerto Internacional de Guadalajara','Guadalajara, Jalisco, México'),
('GHU','Aeropuerto de Gualeguaychú','Gualeguaychú, Argentina'),('GIB','Aeropuerto de Gibraltar','Gibraltar, Reino Unido'),('GPO','Aeropuerto de General Pico','General Pico, Argentina'),('GRU','Aeropuerto Internacional de São Paulo-Guarulhos','São Paulo, Brasil'),('GRW','Aeropuerto de Graciosa','Isla Graciosa, Portugal'),('GRX','Aeropuerto de Granada','Granada, España'),('GUA','Aeropuerto Internacional La Aurora','Ciudad de Guatemala, Guatemala'),
('GYE','Aeropuerto Internacional Jose Joaquin de Olmedo','Guayaquil, Ecuador'),('HAJ','Aeropuerto de Hannover','Hannover, Alemania'),('HAM','Aeropuerto de Hamburgo','Hamburgo, Alemania'),('HAV','Aeropuerto Internacional José Martí','La Habana, Cuba'),('HBX','Aeropuerto de Hubli','Hubballi, Dharwad, India'),('HEA','Aeropuerto de Herat','Herat, Afganistán'),('HEL','Aeropuerto de Helsinki-Vantaa','Helsinki, Finlandia'),('HGL','Aeropuerto de Heligoland','Heligoland, Alemania'),
('HHN','Aeropuerto de Fráncfort-Hahn','Fráncfort, Alemania'),('HIR','Aeropuerto Internacional de Honiara','Honiara, Islas Salomón'),('HKG','Aeropuerto Internacional de Hong Kong','Hong Kong, China'),('HMO','Aeropuerto Internacional General Ignacio Pesqueira García','Hermosillo, México'),('HND','Aeropuerto Internacional de Haneda','Tokio, Japón'),('HOG','Aeropuerto Internacional Frank País','Holguín, Cuba'),('HOR','Aeropuerto de Horta','Isla de Faial, Portugal'),
('HNL','Aeropuerto Internacional de Honolulu','Honolulu, Estados Unidos'),('HOU','Aeropuerto William P. Hobby','Houston, Estados Unidos'),('IBZ','Aeropuerto de Ibiza','Ibiza, España'),('ICN','Aeropuerto Internacional de Incheon','Incheon, Seúl [nota 3]​, Corea del Sur'),('IGR','Aeropuerto Internacional de Puerto Iguazú','Puerto Iguazú, Argentina'),('INV','Aeropuerto de Inverness','Inverness, Reino Unido'),('IPC','Aeropuerto Internacional Mataveri','Isla de Pascua, Chile'),
('IQQ','Aeropuerto Internacional Diego Aracena','Iquique, Chile'),('IRJ','Aeropuerto Capitán Vicente Almandos Almonacid','Ciudad de La Rioja, Argentina'),
('IST','Aeropuerto Internacional Atatürk','Estambul, Turquía'),('IVL','Aeropuerto de Ivalo','Ivalo, Finlandia'),('JAA','Aeropuerto de Jalalabad','Jalalabad, Afganistán'),('JER','Aeropuerto de Jersey','Saint Helier, Reino Unido'),('JFK','Aeropuerto Internacional John F. Kennedy','Nueva York, Estados Unidos'),('JKL','Aeropuerto Nacional de Kálimnos','Pothia (en), Grecia'),('JSR','Aeropuerto de Jessore','Jessore (en), Bangladés'),('JUJ','Aeropuerto Internacional Gobernador Horacio Guzmán','San Salvador de Jujuy, Argentina'),
('KBL','Aeropuerto Internacional de Kabul','Kabul, Afganistán'),('KDH','Aeropuerto Internacional de Kandahar','Kandahar, Afganistán'),('KEF','Aeropuerto Internacional de Keflavík','Reikiavik, Islandia'),('KGD','Aeropuerto de Kaliningrado-Jrabrovo','Kaliningrado, Rusia'),('LAD','Aeropuerto Internacional Quatro de Fevereiro','Luanda, Angola'),('LAS','Aeropuerto Internacional Harry Reid','Las Vegas, Estados Unidos'),('LAX','Aeropuerto Internacional de Los Ángeles','Los Ángeles, Estados Unidos'),
('LCE','Aeropuerto Internacional Golosón','La Ceiba, Honduras'),('LEI','Aeropuerto de Almería','Almería,España'),('LEU','Aeropuerto de Andorra-La Seu','Seo de Urgel, Andorra la Vieja [nota 4]​, España'),('LGG','Aeropuerto de Lieja','Lieja, Bélgica'),('LGS','Aeropuerto Internacional Comodoro Ricardo Salomón','Malargüe, Argentina'),('LGW','Aeropuerto de Gatwick','Londres, Reino Unido'),('LHR','Aeropuerto de Heathrow','Londres, Reino Unido'),('LIM','Aeropuerto Internacional Jorge Chávez','Callao [nota 5]​, Lima, Perú'),
('LIR','Guanacaste Aeropuerto','Guanacaste, Costa Rica'),('LIS','Aeropuerto de Portela','Lisboa, Portugal'),('LTN','Aeropuerto de Londres-Luton','Londres, Reino Unido'),('LUQ','Aeropuerto Brigadier Mayor César Raúl Ojeda','Ciudad de San Luis, Argentina'),('MAD','Aeropuerto Adolfo Suárez Madrid-Barajas','Madrid, España'),('MCS','Aeropuerto de Monte Caseros','Monte Caseros, Argentina'),('MDE','Aeropuerto Internacional José María Cordova','Rionegro, Medellín, Colombia'),('MDQ','Aeropuerto Internacional Astor Piazzolla','Mar del Plata, Argentina'),
('MVD','Aeropuerto Internacional de Carrasco','Montevideo, Uruguay'),('MDZ','Aeropuerto Internacional Gobernador Francisco Gabrielli','Ciudad de Mendoza, Argentina'),('MEC','Aeropuerto de Manta','Manta, Ecuador'),('MGA','Aeropuerto Internacional Augusto C. Sandino','Managua, Nicaragua'),('MTY','Aeropuerto Internacional Mariano Escobedo','Monterrey, México'),('MEX','Aeropuerto Internacional Benito Juárez','Ciudad de México, México'),('MDX','Aeropuerto del Iberá','Mercedes, Argentina'),
('MFM','Aeropuerto Internacional de Macao','Ciudad de Macao, China'),('MIA','Aeropuerto Internacional de Miami','Miami, Estados Unidos'),('MKC','Aeropuerto Urbano Charles B. Wheeler','Kansas City, Estados Unidos'),('MLH','Aeropuerto de Basilea-Mulhouse-Friburgo','Basilea, Mulhouse, Friburgo, Francia'),('MLN','Aeropuerto de Melilla','Melilla, España'),('MPN','Base Aérea de Monte Agradable','Isla Soledad, Reino Unido[nota 6]​'),('MUC','Aeropuerto Internacional de Múnich-Franz Josef Strauss','Munich, Alemania'),
('MXP','Aeropuerto de Milán-Malpensa','Milán,Italia'),('MZR','Aeropuerto de Mazar-e Sarif','Mazar-e Sarif, Afganistán'),('MCO','Orlando International Airport','Orlando, Estados Unidos'),('NAP','Aeropuerto de Nápoles-Capodichino','Nápoles, Italia'),('NLU','Aeropuerto Internacional Felipe Ángeles','Ciudad de México, México'),
('NLK','Aeropuerto de la Isla Norfolk (en)','Kingston, Australia'),('OPO','Aeropuerto de Francisco Sá Carneiro','Oporto, Portugal'),('ORA','Aero Club Orán','San Ramón de la Nueva Orán, Argentina'),('ORD','Aeropuerto Internacional O Hare','Chicago, Estados Unidos'),('ORK','Aeropuerto de Cork','Cork, Irlanda'),('ORY','Aeropuerto de París-Orly','París, Francia'),('OYA','Aeropuerto Dr. Diego Nicolás Díaz Colodrero','Goya, Argentina'),('PBR','Aeropuerto Internacional La Tierra de Dios','Puerto Barrios, Guatemala'),
('PDP','Aeropuerto Internacional de Punta del Este','Maldonado y Punta del Este, Uruguay'),('PDL','Aeropuerto João Paulo II','Isla de São Miguel, Portugal'),('PHL','Aeropuerto Internacional de Filadelfia','Filadelfia, Estados Unidos'),('PIX','Aeropuerto de Pico','Isla del Pico, Portugal'),('PJC','Aeropuerto Doctor Fuster','Pedro Juan Caballero (Paraguay), Paraguay'),('PNA','Aeropuerto de Pamplona','Noáin, España'),('PRA','Aeropuerto General Justo José de Urquiza','Paraná, Argentina'),
('PRQ','Aeropuerto de Presidencia Roque Sáenz Peña','Presidencia Roque Sáenz Peña, Argentina'),('PSY','Aeropuerto de Puerto Argentino/Stanley','Puerto Argentino/Stanley, Reino Unido'),('PTY','Aeropuerto Internacional de Tocumen','Ciudad de Panamá, Panamá'),('PUJ','Aeropuerto Internacional de Punta Cana','Punta Cana, República Dominicana'),('PUQ','Aeropuerto Internacional Presidente Carlos Ibáñez del Campo','Punta Arenas, Chile'),('PXO','Aeropuerto de Porto Santo','Isla de Porto Santo, Portugal'),
('QGY','Aeropuerto Internacional de Györ-Pér','Györ, Hungría'),('QRC','Aeródromo de la Independencia','Rancagua, Chile'),('QSA','Aeropuerto de Sabadell','Sabadell, España'),('RAK','Aeropuerto de Marrakech-Menara','Marrakech, Marruecos'),('RBA','Aeropuerto de Rabat-Salé','Rabat, Marruecos'),('RES','Aeropuerto Internacional de Resistencia','Ciudad de Resistencia, Argentina'),('REU','Aeropuerto de Reus','Reus, Tarragona, España'),('REX','Aeropuerto Internacional de Reynosa','Reynosa,Mexico'),('RGA','Aeropuerto Internacional Gob. Ramón Trejo Noel','Río Grande, Argentina'),
('RHD','Aeropuerto Internacional Termas de Río Hondo','Termas de Río Hondo, Argentina'),('RLO','Aeropuerto Internacional Valle del Conlara','Merlo, Argentina'),('RMU','Aeropuerto Internacional de la Región de Murcia','Región de Murcia, España'),('ROS','Aeropuerto Internacional Rosario Islas Malvinas','Rosario, Argentina'),('RRG','Aeropuerto Sir Gaëtan Duval','Rodrigues, Mauricio'),('RSA','Aeropuerto de Santa Rosa','Ciudad de Santa Rosa, Argentina'),('RTB','Aeropuerto Internacional Juan Manuel Gálvez','Roatán, Islas de la Bahía, Honduras'),
('RUH','Aeropuerto Internacional Rey Khalid','Riad, Arabia Saudita'),('SAL','Aeropuerto Internacional de El Salvador San Óscar Arnulfo Romero y Galdámez','San Salvador, El Salvador'),('SAP','Aeropuerto Internacional Ramon Villeda Morales','San Pedro Sula, Honduras'),('SBZ','Aeropuerto Internacional de Sibiu','Sibiu, Rumania'),('SCU','Aeropuerto Internacional Antonio Maceo y Grajales','Santiago de Cuba, Cuba'),('SCL','Aeropuerto Internacional Arturo Merino Benítez','Santiago de Chile, Chile'),('SDE','Aeropuerto Vicecomodoro Ángel de la Paz Aragonés','Ciudad de Santiago del Estero, Argentina'),
('SDQ','Aeropuerto Internacional José Francisco Peña Gómez','Santo Domingo, República Dominicana'),('SFM','Aeropuerto Internacional de Sacramento','Sacramento, Estados Unidos'),('SFN','Aeropuerto de Sauce Viejo','Sauce Viejo, Argentina'),('SFO','Aeropuerto Interenacional de San Francisco','San Francisco, Estados Unidos'),('SIN','Aeropuerto Internacional de Singapur-Changi','Singapur, Singapur'),('SJO','Aeropuerto Internacional Juan Santamaría','San José, Costa Rica'),('SJZ','Aeropuerto de São Jorge','Isla de São Jorge, Portugal'),('SKG','Aeropuerto Internacional Macedonia','Tesalónica, Grecia'),
('SLA','Aeropuerto Internacional de Salta Martín Miguel de Güemes','Ciudad de Salta, Argentina'),('SMA','Aeropuerto de Santa Maria','Isla de Santa Maria, Portugal'),('SNU','Aeropuerto Internacional Abel Santamaría','Santa Clara, Cuba'),('SUF','Aeropuerto Internacional de Lamezia Terme','Lamezia Terme, Italia'),('SVO','Aeropuerto Internacional de Moscú-Sheremétievo','Moscú,Rusia'),('SVQ','Aeropuerto de Sevilla','Sevilla, España'),('SXB','Aeropuerto de Estrasburgo','Estrasburgo, Francia'),('SYD','Aeropuerto Internacional Kingsford Smith','Sídney, Australia'),
('TER','Aeropuerto de Lajes','Isla Terceira, Portugal'),('TFN','Aeropuerto de Tenerife Norte','Tenerife, España'),('TFS','Aeropuerto de Tenerife Sur','Tenerife, España'),('TGU','Aeropuerto de Toncontín','Tegucigalpa, Honduras'),('THF','Aeropuerto de Berlín-Tempelhof','Berlín, Alemania'),('TLS','Aeropuerto de Toulouse Blagnac','Toulouse, Francia'),('TLV','Aeropuerto Internacional Ben Gurión','Tel Aviv, Israel'),('TPE','Aeropuerto Internacional de Taiwán Taoyuan','Taipéi, Taiwán [nota 9]​'),('TRS','Aeropuerto de Trieste - Friuli Venezia Giulia','Trieste, Italia'),
('TSE','Aeropuerto Internacional de Astaná','Astaná, Kazajistán'),('TTG','Aeropuerto General Enrique Mosconi/Tartagal','Tartagal, Argentina'),('TUR','Aeropuerto de Turku','Turku, Finlandia'),('UIO','Aeropuerto Internacional Mariscal Sucre','Tababela, Ecuador'),('USH','Aeropuerto Internacional Malvinas Argentinas','Ushuaia, Argentina'),('UZU','Aeropuerto de Curuzú Cuatiá','Curuzú Cuatiá, Argentina'),('VCP','Aeropuerto de Viracopos','Sao Paulo, Brasil'),('VDC','Aeropuerto Vitória da Conquista Glauber Rocha','Bahia, Brasil'),('VDM','Aeropuerto Gobernador Edgardo Castello','Viedma, Argentina'),
('VIE','Aeropuerto de Viena-Schwechat','Viena, Austria'),('VKO','Aeropuerto Internacional de Moscú-Vnúkovo','Moscú,| Rusia'),('VLC','Aeropuerto de Valencia','Manises, España'),('VGO','Aeropuerto de Vigo','Vigo,España'),('VLL','Aeropuerto de Villanubla','Valladolid, España'),('VME','Aeropuerto de Villa Reynolds','Villa Mercedes, Argentina'),('VVI','Aeropuerto Internacional Viru Viru','Santa Cruz de la Sierra, Bolivia'),('WLG','Aeropuerto Internacional de Wellington','Wellington, Nueva Zelanda'),('XRY','Aeropuerto de Jerez','Jerez, España'),
('XPL','Aeropuerto Internacional de Comayagua','Comayagua, Honduras'),('YFB','Aeropuerto de Iqaluit','Iqaluit, Canadá'),('YHU','Aeropuerto de Montreal-Saint Hubert','Montreal, Canadá'),('YHZ','Aeropuerto Internacional de Halifax-Stanfield','Halifax, Canadá'),('YOW','Aeropuerto Internacional de Ottawa','Ottawa, Canadá'),('YQB','Aeropuerto Internacional Jean-Lesage de Quebec','Quebec, Canadá'),('YRB','Aeropuerto de Resolute Bay','Resolute, Canadá'),('YUL','Aeropuerto Internacional Pierre Elliott Trudeau','Montreal, Canadá'),
('YVM','Aeropuerto de Qikiqtarjuaq','Qikiqtarjuaq (en), Canadá'),('YVR','Aeropuerto Internacional de Vancouver','Vancouver, Canadá'),('YWG','Aeropuerto Internacional James Armstrong Richardson','Winnipeg, Canadá'),('YYY','Aeropuerto de Mont-Joli','Mont-Joli, Canadá'),('YYZ','Aeropuerto Internacional Toronto Pearson','Toronto, Canadá'),('ZAG','Aeropuerto de Zagreb-Pleso','Zagreb, Croacia'),('ZAZ','Aeropuerto de Zaragoza','Zaragoza, España');

INSERT INTO "Estados" ("id", "Nombre")
VALUES (1, 'Disponible'), (2, 'Ocupado');